version: '3.9'

services:

  crdb:
    image: cockroachdb/cockroach:v21.2.3
    container_name: crdb
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start-single-node --insecure
    volumes:
      - crdb1_data:/cockroach/cockroach-data

volumes:
  crdb1_data:
