version: '3.8'

services:
  mongodb1:
    image: mongo:5-focal
    container_name: mongodb1
    ports:
      - "27017:27017"
    volumes:
      - mongodb1_data:/data/db
    command: mongod --replSet rs0 --bind_ip_all

  mongodb2:
    image: mongo:5-focal
    container_name: mongodb2
    ports:
      - "27018:27017"
    volumes:
      - mongodb2_data:/data/db
    command: mongod --replSet rs0 --bind_ip_all

  mongodb3:
    image: mongo:5-focal
    container_name: mongodb3
    ports:
      - "27019:27017"
    volumes:
      - mongodb3_data:/data/db
    command: mongod --replSet rs0 --bind_ip_all

  mongodb4:
    image: mongo:5-focal
    container_name: mongodb4
    ports:
      - "27020:27017"
    volumes:
      - mongodb4_data:/data/db
    command: mongod --replSet rs0 --bind_ip_all

volumes:
  mongodb1_data:
  mongodb2_data:
  mongodb3_data:
  mongodb4_data:
